name: conexion_celestial_radio
description: Radio Cristiana Conexión Celestial
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
